const prods = [
  {
    id: 1,
    name: "Jus de Pomme",
    price: 2.85,
    instock: 43,
    description: "Jus de Pomme Doux Elopack 1L Bio ",
    image: "../images/pomme.jpg",
  },
  {
    id: 2,
    name: "Chorizo",
    price: 7.70,
    instock: 10,
    description: "Chorizo extra doux 275G Bio ",
    image: "../images/chorizo.jpg",
  },
  {
    id: 3,
    name: "Lait",
    price: 1.72,
    instock: 5,
    description: "Kéfir 500ML Bio ",
    image: "../images/lait.jpg",
  },
  {
    id: 4,
    name: "Thé glacé",
    price: 1.85,
    instock: 4,
    description: "Thé glacé gingembre Charitea Green 330Ml Bio ",
    image: "../images/the-glace.jpg",
  },
  {
    id: 5,
    name: "Saucisses",
    price: 4.99,
    instock: 40,
    description: "Saucisses du Berger x4 230g Bio ",
    image: "../images/saucisses.jpg",
  },
  {
    id: 6,
    name: "Cocktail de légumes",
    price: 29.99,
    instock: 100,
    description: "Cocktail de légumes 75Cl Bio ",
    image: "../images/cocktail-legumes.jpg",
  }, {
    id: 7,
    name: "Patate douce",
    price: 2.25,
    instock: 100,
    description: "Patate douce 500G Bio",
    image: "../images/patate-douce.jpg",
  },
  {
    id: 8,
    name: "Jus Pomme Fraise",
    price: 2.91,
    instock: 100,
    description: "Jus Pomme Fraise 75Cl Bio ",
    image: "../images/fraises.jpg",
  },
  {
    id: 9,
    name: "Figue",
    price: 3.74,
    instock: 100,
    description: "Figue violette x3 Bio ",
    image: "../images/figues.jpg",
  },
  {
    id: 10,
    name: "Fruits Secs",
    price: 7.90,
    instock: 100,
    description:
      "Mélange De Fruits Secs 400g Bio",
    image: "../images/fruits-secs.jpg",
  },
  {
    id: 11,
    name: "Risotto De Légumes",
    price: 4.27,
    instock: 100,
    description:
      "Petit plat bébé 8 mois Bio.",
    image: "../images/risotto-legumes.jpg",
  },
  {
    id: 12,
    name: "Fromage blanc",
    price: 3.49,
    instock: 100,
    description:
      "Fromage blanc de brebis bio origine France Naturalia.",
    image: "../images/fromage-blanc.jpg",
  },
];
